delete from course;
delete from lecture;

insert into course values("3026", "WebApplicationDev");
insert into course values("1016", "MicroProcessorInterface");
insert into course values("4007", "ArtificialIntelligence");
insert into course values("4009", "SystemProgramming");
insert into course values("3027", "ComputerNetwork");
insert into course values("3029", "Cryptography");

insert into lecture (course_id, lecture_id) values ("3026", 1);
insert into lecture (course_id, lecture_id) values ("3026", 2);
insert into lecture (course_id, lecture_id) values ("3026", 3);
insert into lecture (course_id, lecture_id) values ("3026", 4);
insert into lecture (course_id, lecture_id) values ("3026", 5);
insert into lecture (course_id, lecture_id) values ("3026", 6);
insert into lecture (course_id, lecture_id) values ("3026", 7);
insert into lecture (course_id, lecture_id) values ("3026", 8);
insert into lecture (course_id, lecture_id) values ("3026", 9);
insert into lecture (course_id, lecture_id) values ("3026", 10);
insert into lecture (course_id, lecture_id) values ("3026", 11);

insert into lecture (course_id, lecture_id) values ("1016", 1);
insert into lecture (course_id, lecture_id) values ("1016", 2);
insert into lecture (course_id, lecture_id) values ("1016", 3);
insert into lecture (course_id, lecture_id) values ("1016", 4);
insert into lecture (course_id, lecture_id) values ("1016", 5);
insert into lecture (course_id, lecture_id) values ("1016", 6);
insert into lecture (course_id, lecture_id) values ("1016", 7);
insert into lecture (course_id, lecture_id) values ("1016", 8);
insert into lecture (course_id, lecture_id) values ("1016", 9);
insert into lecture (course_id, lecture_id) values ("1016", 10);
insert into lecture (course_id, lecture_id) values ("1016", 11);
insert into lecture (course_id, lecture_id) values ("1016", 12);
insert into lecture (course_id, lecture_id) values ("1016", 13);
insert into lecture (course_id, lecture_id) values ("1016", 14);
insert into lecture (course_id, lecture_id) values ("1016", 15);
insert into lecture (course_id, lecture_id) values ("1016", 16);

insert into lecture (course_id, lecture_id) values ("4007", 1);
insert into lecture (course_id, lecture_id) values ("4007", 2);
insert into lecture (course_id, lecture_id) values ("4007", 3);
insert into lecture (course_id, lecture_id) values ("4007", 4);
insert into lecture (course_id, lecture_id) values ("4007", 5);
insert into lecture (course_id, lecture_id) values ("4007", 6);
insert into lecture (course_id, lecture_id) values ("4007", 7);
insert into lecture (course_id, lecture_id) values ("4007", 8);
insert into lecture (course_id, lecture_id) values ("4007", 9);
insert into lecture (course_id, lecture_id) values ("4007", 10);
insert into lecture (course_id, lecture_id) values ("4007", 11);
insert into lecture (course_id, lecture_id) values ("4007", 12);

insert into lecture (course_id, lecture_id) values ("4009", 1);
insert into lecture (course_id, lecture_id) values ("4009", 2);
insert into lecture (course_id, lecture_id) values ("4009", 3);
insert into lecture (course_id, lecture_id) values ("4009", 4);
insert into lecture (course_id, lecture_id) values ("4009", 5);
insert into lecture (course_id, lecture_id) values ("4009", 6);
insert into lecture (course_id, lecture_id) values ("4009", 7);
insert into lecture (course_id, lecture_id) values ("4009", 8);
insert into lecture (course_id, lecture_id) values ("4009", 9);
insert into lecture (course_id, lecture_id) values ("4009", 10);

insert into lecture (course_id, lecture_id) values ("3027", 1);
insert into lecture (course_id, lecture_id) values ("3027", 2);
insert into lecture (course_id, lecture_id) values ("3027", 3);
insert into lecture (course_id, lecture_id) values ("3027", 4);
insert into lecture (course_id, lecture_id) values ("3027", 5);
insert into lecture (course_id, lecture_id) values ("3027", 6);
insert into lecture (course_id, lecture_id) values ("3027", 7);
insert into lecture (course_id, lecture_id) values ("3027", 8);
insert into lecture (course_id, lecture_id) values ("3027", 9);
insert into lecture (course_id, lecture_id) values ("3027", 10);
insert into lecture (course_id, lecture_id) values ("3027", 11);
insert into lecture (course_id, lecture_id) values ("3027", 12);
insert into lecture (course_id, lecture_id) values ("3027", 13);
insert into lecture (course_id, lecture_id) values ("3027", 14);
insert into lecture (course_id, lecture_id) values ("3027", 15);

insert into lecture (course_id, lecture_id) values ("3029", 1);
insert into lecture (course_id, lecture_id) values ("3029", 2);
insert into lecture (course_id, lecture_id) values ("3029", 3);
insert into lecture (course_id, lecture_id) values ("3029", 4);
insert into lecture (course_id, lecture_id) values ("3029", 5);
insert into lecture (course_id, lecture_id) values ("3029", 6);
insert into lecture (course_id, lecture_id) values ("3029", 7);
insert into lecture (course_id, lecture_id) values ("3029", 8);
insert into lecture (course_id, lecture_id) values ("3029", 9);
insert into lecture (course_id, lecture_id) values ("3029", 10);
insert into lecture (course_id, lecture_id) values ("3029", 11);
insert into lecture (course_id, lecture_id) values ("3029", 12);
insert into lecture (course_id, lecture_id) values ("3029", 13);
insert into lecture (course_id, lecture_id) values ("3029", 14);
