<?php
	session_start();
	require_once("/core/database.php");
	require_once("/core/board.php");
	require_once("../function/feedback.php");
	require_once("../function/login.php");
	require_once("../function/join.php");
	require_once("../function/member.php");
?>